name: hAutoMessages
version: "2.1.1"
main: ru.he3hauka.hautomessages.Main
api-version: '1.16'
softdepend: [PlaceholderAPI]
authors:
  - He3Hauka
website: https://t.me/hplugin
commands:
  hautomessages:
